- hosts: localhost
  tasks:
    - name: Request
      template:
        src: request.j2
        dest: ./request.sh
      tags: template
      register: template_output
    
    - debug: var=template_output.stdout

