- hosts: localhost
  tasks:
    - name: Request
      template:
        src: cartful-jenkins-ansible/request.j2
        dest: cartful-jenkins-ansible/request.sh
      tags: template
      register: template_output
    
    - debug: var=template_output.stdout

